{% set name = "nbodykit" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 2
  script : python setup.py install

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
    - scipy
    - astropy
    - mpi4py-cray
    - runtests
    - pmesh
    - kdcount
    - mpsort
    - bigfile
    - pandas
    - dask >=0.13
    - cachey
    - h5py
    - halotools
    - fitsio
    - classylss >=0.2
    - mcfit
    - sympy
    - numexpr
    - corrfunc

#test:
  # Python imports
#  imports:
#    - nbodykit

about:
  home: http://github.com/bccp/nbodykit
  license: GPL3
  summary: 'Analysis kit for large-scale structure datasets, the massively parallel way'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
