# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c

os:
  - linux
  - osx

env:
    global:
        - DESTINATION_CONDA_CHANNEL="bccp"
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/miniconda"

        # Defines BINSTAR_TOKEN for your binstar channel
        - secure: "0fIuL2KuDNRVWFERTa3Z6oVyFSc01CISoJWEui+oLCjkSceN68UsHbOQ/o5lv2SA6JFCOGwqkTlcf+51ewPG4kt7mqYUS+2snNeSxA+2/fYfI/pjgbePVsN6uhke0UHUOgljEvy9qUlfZ7Ai2q2/Z/ijPFn01dd7vw0fItZZJ1vnQtq7L1bYOkK5jh1T0ns3FW0MG8KnT1j+m89ZIT4fsdQw/l8vnu5mEev4bvUUqXQ2dRDHR+/ZLme1wj/HHXbiSR7+i+l3N1OJpc2fWZKiZrnM+Tyl3xwG17FvSZ6qHoay5wwyW/hy2foce4uBSbVHmQQVcgBzLSKxB0JvPNadnsi3Vs2ktgKT1eigxQEak1W6YO6qZa7272AvlVkhTIqMzQ6YA/Skr+1kv5xYMxKWKhzTRKOlirrBtku02+dKZ3mgNxlTzxjFBPbZrixqz3eNsOGhKvNFzGn1vdtwSe5uKODK1nB+CWWdCX4AwmfmE06grmGmgkuTRL0WqbDuM8f0L5ulyGIwB06KpUtpG/duwtxC/2puZGwkvXbjb0R8SrR1+6JB9d7D0dLcdxXgw/35OFn0CDB9NodQ23K8MxbzBbPaBXrvqMQ3IU7kWoguqjSK7yjDw6AQTX7691VFMUhgqjjOL36bhrF+f3FeJlII3zO3SJi1qmwK3uVFAsHPkZY="

        # The python build restriction MUST be set at the moment, though it
        # can have any value. The setting below avoids known-bad builds on
        # python 2.6 and 3.3 for some packages.
        - PYTHON_BUILD_RESTRICTIONS="2.7*|>=3.4"

        - NUMPY_BUILD_RESTRICTION="numpy <1.13"
        # The value below needs to be set but will be ignored.
        - CONDA_NPY="1.11"
        - CONDA_VERSION=4.2*

# Matrix is fully specified (for now) by os versions

install:
    # Install and set up miniconda.
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $CONDA_INSTALL_LOCN
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true

    - PIN_FILE_CONDA=${CONDA_INSTALL_LOCN}/conda-meta/pinned
    - echo "conda ${CONDA_VERSION}" > $PIN_FILE_CONDA

    - conda update --quiet conda

    # Install a couple of dependencies we need for sure.
    - conda install --quiet --yes astropy anaconda-client jinja2 cython pycrypto
    - conda install ruamel_yaml

    # needed for mac and classylss
    - conda install gcc

    - conda install conda-build

    # Install conda-build-all
    - conda install -c conda-forge conda-build-all=1.0.2

    # so we can grab compiled packages for dependencies
    - conda config --add channels bccp

    # so we can grab compiled packages for dependencies
    - conda config --add channels astropy

    # conda build all is incompatible with anaconda-client 1.6.3
    - conda install anaconda-client=1.6.2

    # To ease debugging, list installed packages
    - conda info -a

script:
    # Only upload if this is NOT a pull request.
    - INSPECT="--inspect-channels bccp"
    - UPLOAD="";
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        if [ $TRAVIS_REPO_SLUG = "bccp/conda-channel-bccp" ]; then
          echo "Uploading enabled";
          UPLOAD="--upload-channels $DESTINATION_CONDA_CHANNEL";
        fi;
      fi
    # Get ready to build.
    - python extrude_recipes requirements.yml
    # Packages are uploaded as they are built.
    - if [[ -d recipes ]]; then conda build-all recipes --matrix-conditions "python $PYTHON_BUILD_RESTRICTIONS" "$NUMPY_BUILD_RESTRICTION"  $INSPECT $UPLOAD; fi
