- name: mpi4py_test
  version: 0.0.10
  numpy_compiled_extensions: false
  excluded_platforms:
      - 'win-64'
      
- name: kdcount
  version: 0.3.21
  numpy_compiled_extensions: false
  excluded_platforms:
      - 'win-64'