- name: mpi4py_test

- name: runtests

- name: kdcount

- name: pfft-python

- name: classylss

- name: bigfile

- name: mpsort

- name: pmesh

- name: nbodykit

- name: abopt

- name: cachey

- name: fastpm
