# Build specific versions by specifying 'version'
# If 'version' not specified, latest release from pypi is built
# To build past versions in addition, specify a 'past_versions' list

- name: mpi4py-cray
  pypi_name: mpi4py

- name: mpi4py_test

- name: runtests

- name: kdcount

- name: pfft-python

- name: classylss

- name: bigfile

- name: mpsort

- name: pmesh

- name: nbodykit
  past_versions: [0.1.11]

- name: cachey

- name: fitsio
