{% set name = "Corrfunc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/nickhand/Corrfunc.git
  git_tag: master

build:
  number : 2

requirements:
  build:
    - '{{ compiler("c") }}' # [linux]

  host:
    - python
    - numpy
    - future
    - gsl

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'
    - gsl
    - future

test:
  # Python imports
  imports:
    - Corrfunc
    - Corrfunc.tests

about:
  #home: The package home page
  license: MIT
  summary: 'Blazing fast correlation functions on the CPU'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
