{% set name = "cachey" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 0
  script : python setup.py install
  
requirements:
  build:
    - python
    - setuptools
    - heapdict

  run:
    - python
    - heapdict

test:
  # Python imports
  imports:
    - cachey

about:
  home: http://github.com/mrocklin/cachey/
  license: BSD
  summary: 'Caching mindful of computation/storage costs'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
