{% set build = 0 %}
{% set version = '0.0.0' %}
{% set major = version.rpartition('.')[0] %}

package:
    name: prgenv-gnu-impl_linux-64
    version: {{ version }}

build:
    number: {{ build }}
    skip: True  # [win]
    skip: True  # [osx]
    features:
      - host.{{ crayhost }}

requirements:
    build:
      - host.{{ crayhost }}
    host:
      - host.{{ crayhost }}
    run:
      - host.{{ crayhost }}

test:
    files:
      - tests/helloworld.c
      - tests/helloworld.cxx
      - tests/helloworld.f
      - tests/helloworld.f90

#run_exports:
#  strong:
#    - prgenv-gnu_linux-64[host.{{ crayhost }}]

extra:
    recipe-maintainers:
        - rainwoodman
