version: 2

jobs:
  build:
    docker:
      - image: continuumio/conda_builder_linux:5.11-5.2-1-4
    steps:
      - checkout
      - run:
          name: Check conda
          command: |
            source /opt/miniconda/bin/activate
            conda info
      - run:
          name: Build
          command: |
            bash .circleci/rebuild.sh
      - run:
          name: Print the Current Time
          command: date

