package:
  name: kdcount
  version: "{{version}}"

source:
  fn: kdcount-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/k/kdcount/kdcount-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - kdcount = kdcount:main
    #
    # Would create an entry point called kdcount that calls kdcount.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - cython

  run:
    - python
    - numpy
    - cython

test:
  # Python imports
  imports:
    - kdcount
    - kdcount.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/rainwoodman/kdcount
  license: GPL3
  summary: 'A slower KDTree cross correlator'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
