{% set name = "classylss" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 0
  script : python setup.py install --single-version-externally-managed --record rec.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - astropy
    - gcc
    - cython

  run:
    - python
    - cython
    - numpy x.x
    - astropy
    - libgcc

test:
  # Python imports
  imports:
    - classylss

about:
  home: http://github.com/nickhand/classylss
  license: GPL3
  summary: 'python binding of CLASS for large-scale structure calculations'
  license_family: GPL3

extra:
  recipe-maintainers:
    - rainwoodman
