{% set name = "fitsio" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 0
  script : which gcc; python setup.py install

requirements:
  build:
    - python
    - numpy x.x
    - gcc

  run:
    - python
    - numpy x.x
    - libgcc

test:
  # Python imports
  imports:
    - fitsio

about:
  home: https://github.com/esheldon/fitsio
  license: GPL
  summary: 'A full featured python library to read from and write to FITS files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
