{% set name = "fitsio" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 0
  script :
    - source /usr/common/contrib/bccp/conda-channel-bccp/nersc_profile.sh
    - python setup.py install

requirements:
  build:
    - python
    - numpy {{ '{{ numpy }}' }}

  run:
    - python
    - numpy {{ '{{ numpy }}' }}

test:
  # Python imports
  imports:
    - fitsio

about:
  home: https://github.com/esheldon/fitsio
  license: GPL
  summary: 'A full featured python library to read from and write to FITS files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
