{% set name = "fitsio" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 5

requirements:
  build:
    - '{{ compiler("c") }}'

  host:
    - python
    - numpy
    - bzip2

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'

test:
  # Python imports
  imports:
    - fitsio

about:
  home: https://github.com/esheldon/fitsio
  license: GPL
  summary: 'A full featured python library to read from and write to FITS files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
