{% set name = "pmesh" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 0
  script :
      - source /usr/common/contrib/bccp/conda-channel-bccp/nersc_profile.sh
      - python setup.py install

requirements:
  build:
    - python
    - cython
    - numpy {{ '{{ numpy }}' }}
    - mpi4py-cray
    - mpsort
    - pfft-python

  run:
    - python
    - cython
    - numpy {{ '{{ numpy }}' }}
    - mpi4py-cray
    - mpsort
    - pfft-python

test:
  # Python imports
  imports:
    - pmesh
    - pmesh.tests

about:
  #home: The package home page
  license: GPL3
  summary: 'Particle Mesh in Python'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
