{% set name = "mpsort" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 1
  script : 
      - source /usr/common/contrib/bccp/conda-channel-bccp/nersc_profile.sh
      - python setup.py install

requirements:
  build:
    - python
    - cython
    - numpy
    - mpi4py

  run:
    - python
    - numpy
    - mpi4py

test:
  # Python imports
  imports:
    - mpsort
    - mpsort.tests

about:
  home: http://github.com/rainwoodman/mpsort
  license: BSD-2-Clause
  summary: 'python binding of MP-sort, a peta scale sorting routine'
  license_family: BSD

extra:
  recipe-maintainers:
    - rainwoodman
