{% set build = 0 %}
{% set version = '0.0.0' %}
{% set sha256 = 'f699bff21db0125d8cccfe79518b77641cd83628725a1e1ed3e45633496a82d7' %}
{% set major = version.rpartition('.')[0] %}

package:
    name: crayprgenv-gnu
    version: {{ version }}

build:
    number: {{ build }}
    skip: True  # [win]
    skip: True  # [osx]

extra:
    recipe-maintainers:
        - rainwoodman
